src/mutations/users.mutation.ts
=> Update registration user response

src/index.ts, src/modules/settings/index.tsx, src/queries/settings.query.ts
This PR fix this both errors:
And there is a little refactor
=> fix: import errors

src/index.ts, src/modules/index.ts, src/modules/leads/index.ts, src/mutations/index.ts, src/mutations/leads.mutation.ts, src/types/index.ts, src/types/leads.ts
=> Feat/kp 63 Create new lead

src/queries/users.query.ts
These fields are necessary when creating a new lead. (add in users.query.ts)
- default_company_branch
- default_company
=> Add missing field to get user info

package.json, src/modules/messages/index.ts, src/mutations/messages.mutation.ts, test/message.test.ts
Allow user to delete all his msg
=> feat; delete all msg

package.json, src/modules/messages/index.ts, src/mutations/messages.mutation.ts, test/message.test.ts
=> feat: message share

package.json, src/modules/users/index.ts, src/queries/users.query.ts, src/types/users.ts, test/user.test.ts
=> feat: add user social property

package.json, src/modules/messages/index.ts, src/mutations/messages.mutation.ts, src/queries/messages.query.ts, src/types/messages.ts, test/message.test.ts
- Allow dev to get message by slug and displayname
=> Feat: add get message by slug

package.json, src/queries/messages.query.ts, src/types/messages.ts
- Add message tags to structure
=> refact: add message tags

package.json, src/modules/auth/index.ts, src/modules/messages/index.ts, src/modules/users/index.ts, src/mutations/messages.mutation.ts, src/queries/messages.query.ts, src/queries/users.query.ts, src/types/leads.ts, src/types/users.ts, test/message.test.ts, test/user.test.ts
- Add message view
- Add get user by displayname
=> feat: social updates

package.json, src/modules/messages/index.ts, src/mutations/messages.mutation.ts, test/message.test.ts
=> feat: dislike msg

package.json, src/queries/messages.query.ts, src/types/messages.ts
- Add total like, dislike, view, shared
=> feat: add total likes

package.json, src/queries/messages.query.ts, src/types/messages.ts
Reverts bakaphp/kanvas-core-js#273
=> Revert " feat: add created at"

package.json, src/queries/messages.query.ts, src/types/messages.ts
Reverts bakaphp/kanvas-core-js#274
=> Revert "Revert " feat: add created at""

package.json, src/modules/messages/index.ts, test/message.test.ts
Move group msg to the correct getEntity format
=> refact: group message

package.json, src/modules/leads/index.ts, src/modules/messages/index.ts, src/types/messages.ts, test/message.test.ts
Hotfix SDK return message type to follow the other module standard
=> hotfix: return message type

.github/workflows/main.yml, .github/workflows/npm-publish.yml, package.json, src/modules/settings/index.tsx, src/queries/settings.query.ts, src/types/settings.ts, test/customFields.test.ts, test/setupClient.ts
- Add appSettings, appSetting(key)
- Add test
=> feat: add get app setting

package.json, src/queries/companies.query.ts, test/company.test.ts
- Add user custom fields + photo
=> feat: add user custom fields

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, src/types/messages.ts, test/message.test.ts
- Add suggest query method for messages
=> feat: suggest msg

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, test/message.test.ts
=> hotfix: empty suggestion

test/message.test.ts
i'll uncomment this test until the search of the messages get fixed
=> chore: Comment out a test case in message.test file

package.json, src/modules/commerce/cart/index.ts, src/mutations/commerce.mutation.ts, src/mutations/companies.mutation.ts, src/types/commerce.ts, test/cart.test.ts
Provide Get Cart Query for marketplace implementation
=> feat: cart query

package.json, src/modules/follows/index.ts, src/modules/users/index.ts, src/mutations/follows.mutation.ts, src/mutations/users.mutation.ts, src/queries/follows.query.ts, src/queries/users.query.ts, src/types/users.ts, test/followers.test.ts, test/message.test.ts, test/messageFiles.test.ts, test/user.test.ts
- Add user share
- Add user get by id
- user followers
=> feat: user profile methods

package.json, src/queries/follows.query.ts, src/types/users.ts
=> feat: add event participant

package.json, src/queries/app.query.ts, src/types/app.ts
=> refact: app user query

package.json, src/index.ts, src/modules/event/index.ts, src/modules/index.ts, src/mutations/event.mutation.ts, src/mutations/index.ts, src/queries/event.query.ts, src/queries/index.ts, src/types/events.ts, src/types/index.ts
- Added queries for fetching event details, participants, categories, statuses, and types.
- Added mutations for creating and updating events.
=> feat: Implement Event queries and mutations

package.json, src/modules/messages/index.ts, src/mutations/users.mutation.ts, src/queries/app.query.ts, src/queries/follows.query.ts, src/queries/messages.query.ts, src/queries/users.query.ts, src/types/app.ts, src/types/messages.ts, src/types/users.ts, test/message.test.ts
=> feat: user like messages

package.json, src/queries/messages.query.ts
- Add user block and follow to in msg
=> refact: messages query

package.json, src/modules/commerce/cart/index.ts, src/types/commerce.ts, test/cart.test.ts, test/message.test.ts, test/roles.test.ts
=> refact: add to cart

package.json, src/modules/follows/index.ts
- no-cache to follower and following list
=> refact: no-cache on followers list

package.json, src/queries/users.query.ts
- Add total blocked user to profile
=> feat: add total blocked

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, src/types/messages.ts, test/message.test.ts
Add for you feed in SDK to get user recommended messages
=> feat: add message for you feed

package.json, src/modules/commerce/orders/index.ts, src/mutations/commerce.mutation.ts, src/types/commerce.ts, test/order.test.ts
=> refactor: add mutation generateOrderPaymentIntent

package.json, src/modules/messages/index.ts, src/mutations/messages.mutation.ts, test/message.test.ts
=> feat: add restore msg

package.json, src/types/commerce.ts
Allow OrderCartInput to send metadata
=> refactor: order cart input

package.json, src/queries/locations.query.ts
=> feat: add flags

package.json, src/types/custom-fields.ts
Allow custom fields visibility
=> refact: allow custom field visibility

jest.config.js, package.json, src/types/messages.ts, test/message.test.ts
=> update message type

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, src/types/messages.ts, test/message.test.ts
Add childer and make it dynamic
=> feat: children to message

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, src/types/messages.ts, test/message.test.ts
=> feat: message channel

package.json, src/types/commerce.ts
=> refact: discount response

package.json, src/modules/commerce/cart/index.ts
=> hotfix: cart cache

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts, test/cart.test.ts, test/message.test.ts
Allow to filter message by multiple tags
=> feat: refactor message tag filter

package.json, src/modules/commerce/orders/index.ts, src/mutations/commerce.mutation.ts
=> refactor payment intent

package.json, src/mutations/commerce.mutation.ts, src/types/commerce.ts
=> refact: order metadata

package.json, src/modules/inventory/index.ts, src/queries/inventory.query.ts
Allow to search product by sku
=> feat: allow search by sku

package.json, src/modules/filesystem/index.ts
=> hotfix android upload files

package.json
Update the version number in the package configuration to reflect the latest release.
=> Bump version to 0.29.1

package.json
Update the version number in the package file to reflect the new release.
=> Bump version to 0.29.2

src/modules/follows/index.ts, src/queries/follows.query.ts, test/followers.test.ts
Describe your changes in detail.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here (if you write `fixes #num`
or `closes #num`, the issue will be automatically closed when the pull is accepted.)
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.
What types of changes does your code introduce? Put an `x` in all the boxes that apply:
Go over all the following points, and put an `x` in all the boxes that apply.
Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous …
=> feat: add user recommendations query and tests for follow recommendations

package.json
Update the version number in the package configuration to 0.30.3.
=> Bump version to 0.30.3

package.json, src/queries/follows.query.ts
Increment the package version and add a photo URL field to the user recommendations query.
=> Update version to 0.31.1 and enhance user recommendations query

package.json, src/queries/follows.query.ts
Enhance the robustness of API requests by implementing better error handling and logging mechanisms. This update aims to provide clearer feedback during failures and improve overall user experience.
=> Improve error handling in API requests

package.json, src/queries/users.query.ts
Increment the version number and enhance the user query by including the unread notifications field.
=> Update version to 0.32.3 and add unread notifications to user query

package.json, src/modules/messages/index.ts, src/queries/messages.query.ts
Improve the GET_MESSAGES_LIKED_BY_USER query to support options for including child messages. Update the package version to 0.32.5.
=> Enhance GET_MESSAGES_LIKED_BY_USER query and update version

package.json
Increment the version number in package.json to reflect the latest release.
=> Update version to 0.32.6
